[features]
seeds = false
[programs.localnet]
grantive = "BydUvE2y1jF3q6CozVgigi2gE7FF3L7tosd9Zmwh9n4n"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/irshad/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
